# This is a basic workflow that is manually triggered

name: Release okteto/bin

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'tag'
        description: 'tag'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASS }}'

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3.3.1
      with:
        qemu-version: latest
        buildx-version: latest

    - name: "Push"
      working-directory: images/bin
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --output "type=image,push=true" \
          --build-arg COMMIT_SHA=${{ github.sha }} -t okteto/bin:${{ github.event.inputs.tag }} .
